import Head from "next/head";
import Footer from "../../components/Shared/Footer";
import Header from "../../components/Shared/Header";

const index = () => {
    return (
        <>
        <Head>
     <title>Login-</title>
     <meta name="description" content="Generated by create next app" />
     <link rel="icon" href="/favicon.ico" />
   </Head>
   <Header></Header>

   <main>
   <section className="container mx-auto py-10">
     <div className="title-area py-20 bg-gradient-to-r from-primary to-primary/10">
     <h2 className="text-4xl text-white font-bold text-center"> Login</h2>
     </div>
        
       
     </section>
   </main>

  <Footer></Footer>
 </>
    );
};

export default index;