import Head from "next/head";
import { useState } from "react";
import Header from "../../../components/Dashboard/Header";
import Sidebar from "../../../components/Dashboard/Sidebar";
import { FaEdit, FaTrash } from 'react-icons/fa';
import Link from "next/link";


const index = () => {
  const [close, setClose] = useState(false);
  return (
    <>
      <Head>
        <title>My Books</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white flex items-start justify-center">
        <div className={close ? 'w-0 overflow-hidden transition-all duration-300 translate-x-[-100%]' : 'transition-all duration-300 translate-x-0 w-60'}>
          <Sidebar />
        </div>
        <section className="w-full">
            <Header close={close} setClose={setClose}></Header>
            <div className="m-6">
                <h1 className="text-2xl pb-5 rounded-md">My Books</h1>
                <div className="overflow-x-auto">
                  <table className="table w-full">
                    <thead>
                      <tr>
                        <th className="bg-secondary/10">SL</th>
                        <th className="bg-secondary/10">Book Name</th>
                        <th className="bg-secondary/10">Author</th>
                        <th className="bg-secondary/10">Complete</th>
                        <th className="w-10 bg-secondary/10">Actions</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td className="bg-primary/10">1</td>
                        <td className="bg-primary/10">The Art of War: Complete Text and Commentaries</td>
                        <td className="bg-primary/10">Sun Tzu</td>
                        <td className="bg-primary/10">No</td>
                        <td className="bg-primary/10"><Link href={'/book'}  className="btn btn-primary mx-2 btn-block"> Read</Link></td>
                      </tr>
                      <tr>
                        <td className="bg-primary/10">2</td>
                        <td className="bg-primary/10">How To Stop Worrying And Start Living</td>
                        <td className="bg-primary/10">Dale Carnegie	</td>
                        <td className="bg-primary/10">No</td>
                        <td className="bg-primary/10"><Link href={'/book'}  className="btn btn-primary mx-2 btn-block"> Read</Link></td>
                      </tr>
                      <tr>
                        <td className="bg-primary/10">3</td>
                        <td className="bg-primary/10">Purchasing and Supply Chain Management</td>
                        <td className="bg-primary/10">	Brian Fairrington</td>
                        <td className="bg-primary/10">Yes</td>
                        <td className="bg-primary/10"><Link href={'/book'}  className="btn btn-primary mx-2 btn-block">Read Again</Link></td>
                      </tr>
                      
                    </tbody>
                  </table>
                </div>
            </div>
        </section>
      </main>
    </>
  );
};

export default index;