import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '../components/Shared/Header'
import Footer from '../components/Shared/Footer'
import PricingPlans from "../components/HomePage/PricingPlans";
import ApplyForTeacher from "../components/HomePage/ApplyForTeacher";
import HowDoesItWorks from "../components/HomePage/HowDoesItWorks";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Book Society-</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-base-100'>
        <Header></Header>
          <PricingPlans></PricingPlans>
          <HowDoesItWorks></HowDoesItWorks>
          <ApplyForTeacher></ApplyForTeacher>
        <Footer></Footer>
      </main>
    </>
  )
}
