import Head from "next/head";
import Image from "next/image";
import Header from "../components/Shared/Header";
import Footer from "../components/Shared/Footer";
import PricingPlans from "../components/HomePage/PricingPlans";
import ApplyForTeacher from "../components/HomePage/ApplyForTeacher";
import HowDoesItWorks from "../components/HomePage/HowDoesItWorks";
import BooksOfTheMonth from "../components/HomePage/BooksOfTheMonth";
import BooksCategories from "../components/HomePage/BooksCategories";
import BestSellers from "../components/HomePage/BestSellers";

export default function Home() {
	return (
		<>
			<Head>
				<title>
					Book Society- Books Society is place where user can read books and
					test their skill and communicate with like minded.
				</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="bg-base-100">
				<Header></Header>
				<BooksOfTheMonth></BooksOfTheMonth>
				<BooksCategories></BooksCategories>
        <BestSellers></BestSellers>
				<HowDoesItWorks></HowDoesItWorks>
				<PricingPlans></PricingPlans>
				<ApplyForTeacher></ApplyForTeacher>
				<Footer></Footer>
			</main>
		</>
	);
}
