import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Header from '../components/Shared/Header'
import Footer from '../components/Shared/Footer'
import MainHero from '../components/HomePage/MainHero'
import Service from '../components/HomePage/Service'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Book Society- Books Society is place where user can read books and test their skill and communicate with like minded.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-base-100'>
        <Header></Header>
        <MainHero></MainHero>
        <Service></Service>
        <Footer></Footer>
      </main>
    </>
  )
}
