import Head from "next/head";
import { useState } from "react";
import { getSession, useSession } from "next-auth/react";
import Header from "../../../components/Dashboard/Header";
import Sidebar from "../../../components/Dashboard/Sidebar";
import FeatureSide from "../../../components/Dashboard/FeatureSide";
import Cate from "../../../components/Dashboard/Chart/Cate";

const profile = () => {
	const [close, setClose] = useState(false);
	const { data: session } = useSession();

	return (
		<>
			<Head>
				<title>Dashboard</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="bg-white flex items-start justify-center">
				<div
					className={
						close
							? "w-0 overflow-hidden transition-all duration-300 translate-x-[-100%]"
							: "transition-all duration-1000 translate-x-0 w-60"
					}
				>
					<Sidebar />
				</div>
				<section className="grid grid-cols-8 w-full">
					<div className="col-span-6">
						<Header close={close} setClose={setClose}></Header>

						<div className="user-info flex m-5 justify-between">
							<div className="card rounded-lg shadow-lg mx-auto p-10 m-10 w-5/12">
                            <div className="py-10">
									<h2 className="text-2xl text-center">User Profile </h2>
								</div>
								<div className="flex justify-center items-center">
                                    <div className="img-area">
                                    <div className="w-20 rounded-full ring ring-primary ring-offset-base-100 ring-offset-2">
										<img
											src={"https://i.ibb.co/xm2hjv2/linkedin.jpg"}
											className="ring-primary rounded-full"
										/>
									</div>
                                    </div>
								
									<div className="info ml-5">
										<h2 className="text-xl">
											
											User Name : {session?.user.email.slice(0, -10)}
										</h2>
										<h2 className="text-xl">
										
											User Email : {session?.user.email}
										</h2>
                                        <h2 className="text-xl">
											{" "}
											User Role : Admin
										</h2>
                                        <h2 className="text-xl font-bold">
											{" "}
											Subscription Days Left : 358 Days
										</h2>
									</div>
								</div>
							</div>

							<div className="card rounded-lg shadow-lg mx-auto p-10 m-10 w-5/12 ">
								<div className="py-10 bg-accent/10">
									<h2 className="text-2xl text-center">Payment History</h2>
								</div>

								<div className="overflow-x-auto">
									<table className="table w-full">
										<thead>
											<tr>
												<th className="bg-secondary/10"></th>
												<th className="bg-secondary/10">Subscription Type</th>
												<th className="bg-secondary/10">Date</th>
												<th className="bg-secondary/10">Cost</th>
											</tr>
										</thead>
										<tbody >
											<tr>
												<th className="bg-primary/10">1</th>
												<td className="bg-primary/10">Yearly</td>
												<td className="bg-primary/10">12-28-22</td>
												<td className="bg-primary/10">$99</td>
										
											</tr>

											<tr>
                                            <th className="bg-primary/10">2</th>
												<td className="bg-primary/10">Free</td>
												<td className="bg-primary/10">12-21-22</td>
												<td className="bg-primary/10">$0</td>
											</tr>

									
										</tbody>
									</table>
								</div>
							</div>
						</div>
                        <div className="card rounded-lg shadow-lg mx-auto p-10 m-10 w-10/12 ">
                        <div className="py-10 bg-accent/10">
									<h2 className="text-2xl text-center">Average Spending Time</h2>
								</div>
                          
                        <Cate></Cate>
                        </div>
                       
					</div>

					<div className="col-span-2">
						<FeatureSide />
					</div>
				</section>

				<section></section>
			</main>
		</>
	);
};

export default profile;
