import Head from "next/head";
import Link from "next/link";
import BooksCard from "../../components/Books/BooksCard";
import Newsletter from "../../components/HomePage/Newsletter";
import Divider from "../../components/Shared/divider";
import Footer from "../../components/Shared/Footer";
import Header from "../../components/Shared/Header";
import { getBooks } from "../api/books";

const index = ({ booksData }) => {
	return (
		<>
			<Head>
				<title>Books</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header></Header>

			<main>
				<section className="pb-10">
				<div className="title-area py-5 bg-neutral">
					<div className="container mx-auto">
						<div className="w-6/12 mx-auto text-white">
						<h2 className="text-4xl  font-bold text-center">All the Available Books</h2>
						<div className=" flex justify-center my-10">
				<Divider></Divider>		
				</div>
						<p className="mx-auto text-center pb-10">
							Improving vocabulary and language skills: Reading exposes you to
							new words and concepts, which can help to expand your vocabulary
							and improve your language skills. Promoting concentration and
						
						</p>
						</div>
						
					</div>
					</div>
					<div className="container mx-auto">
					<div className="grid  grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 mx-auto">
							{booksData.map((books) => (
								<BooksCard key={books._id} bookData={books}></BooksCard>
							))}
						</div>
					</div>
				</section>
			</main>
			<Newsletter></Newsletter>
			<Footer></Footer>
		</>
	);
};

export async function getStaticProps() {
	try {
		const booksData = await getBooks();
		if (!booksData) {
			return {
				notFound: true,
				revalidate: 60,
			};
		}
		return {
			props: {
				booksData: JSON.parse(JSON.stringify(booksData)),
			},
			revalidate: 60,
		};
	} catch (error) {
		console.log(error);
	}
}

export default index;
