import Head from "next/head";
import Header from "../../../components/Dashboard/Header";
import Sidebar from "../../../components/Dashboard/Sidebar";


const index = () => {
  return (
    <>
      <Head>
        <title>All Reviews</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white">
        <section className="grid grid-cols-10">
          <div className="col-span-2">
            <Sidebar/>
          </div>
          <div className="col-span-8">
            <Header></Header>
            <div>
                {/* Your code will go here and you can remove the h1 bellow. */}
                <h1 className="text-5xl m-6 p-5 rounded-md bg-slate-400">All Reviews</h1>
            </div>
          </div>
        </section>
      </main>
    </>
  );
};

export default index;